from django.urls import path, include
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('',                        views.accueil,               name='accueil'),
    path('accueil/',                views.accueil,               name='accueil_page'),
    path('transport/',              lambda request: redirect('transport_bons'), name='transport_index'),
    path('production/', include('reporting.production_urls')),
    path('transport/bons-transport/',      views.transport_bons,               name='transport_bons'),
    path('transport/gasoil/',              views.transport_gasoil,             name='transport_gasoil'),
    path('transport/couts-par-nature/',    views.transport_couts_nature,       name='transport_couts_nature'),
    path('transport/facturation-client/',  views.transport_facturation_client, name='transport_facturation_client'),
    path('transport/rentabilite/',         views.transport_rentabilite,        name='transport_rentabilite'),
    path('achats/',                        lambda request: redirect('achats_overview'), name='achats_index'),
    path('achats/vue-ensemble/',           views.achats_overview,               name='achats_overview'),
    path('achats/demandes-achat/',         views.achats_purchase_requests,      name='achats_purchase_requests'),
    path('achats/demandes-prix/',          views.achats_rfq,                    name='achats_rfq'),
    path('achats/bons-commande/',          views.achats_purchase_orders,        name='achats_purchase_orders'),
    path('achats/suivi-livraisons/',       views.achats_delivery_tracking,      name='achats_delivery_tracking'),
    path('achats/fournisseurs/',           views.achats_suppliers,              name='achats_suppliers'),
    path('achats/synthese-pdf/',           views.achats_synthese_pdf,           name='achats_synthese_pdf'),
    path('parc/',                          views.parc_module,                    name='parc_index'),
    path('parc/module/',                   views.parc_module,                    name='parc_module'),
    path('parc/debug/',                    views.parc_debug,                     name='parc_debug'),
    path('parc/demandes/',                 views.parc_demandes,                  name='parc_demandes'),
    path('parc/demandes/<int:demande_id>/',views.parc_demande_detail,            name='parc_demande_detail_legacy'),
    path('parc/demande/<int:demande_id>/', views.parc_demande_detail,            name='parc_demande_detail'),
    path('parc/equipements/',              views.parc_equipements,               name='parc_equipements'),
    path('parc/equipements/export-pdf/',   views.parc_equipements_pdf,           name='parc_equipements_pdf'),
    path('parc/equipements/export-excel/', views.parc_equipements_excel,         name='parc_equipements_excel'),
    path('parc/equipements/export-csv/',   views.parc_equipements_csv,           name='parc_equipements_csv'),
    path('parc/disponibilite/',            views.parc_disponibilite,             name='parc_disponibilite'),
    path('parc/disponibilite/export-pdf/', views.parc_disponibilite_pdf,         name='parc_disponibilite_pdf'),
    path('parc/disponibilite/export-excel/', views.parc_disponibilite_excel,     name='parc_disponibilite_excel'),
    path('parc/disponibilite/export-csv/', views.parc_disponibilite_csv,         name='parc_disponibilite_csv'),
    path('parc/ordres/',                   views.parc_ordres,                    name='parc_ordres'),
    path('parc/ordres/export-pdf/',        views.parc_ordres_pdf,                name='parc_ordres_pdf'),
    path('parc/ordres/export-excel/',      views.parc_ordres_excel,              name='parc_ordres_excel'),
    path('parc/ordres/export-csv/',        views.parc_ordres_csv,                name='parc_ordres_csv'),
    path('parc/interventions/',            views.parc_interventions,             name='parc_interventions'),
    path('parc/interventions/export-pdf/', views.parc_interventions_pdf,         name='parc_interventions_pdf'),
    path('parc/interventions/export-excel/', views.parc_interventions_excel,     name='parc_interventions_excel'),
    path('parc/interventions/export-csv/', views.parc_interventions_csv,         name='parc_interventions_csv'),
    path('parc/couts/',                    lambda request: redirect('parc_ordres'), name='parc_couts'),
    path('parc/couts/export-pdf/',         views.parc_couts_pdf,                 name='parc_couts_pdf'),
    path('parc/couts/export-excel/',       views.parc_couts_excel,               name='parc_couts_excel'),
    path('parc/couts/export-csv/',         views.parc_couts_csv,                 name='parc_couts_csv'),
    path('parc/fournisseurs/',             views.parc_fournisseurs,               name='parc_fournisseurs'),
    path('parc/equipements/<int:equipment_id>/', views.parc_equipment_detail,    name='parc_equipment_detail'),
    # Compat anciennes routes
    path('maintenance/',                   lambda request: redirect('parc_module'), name='parc_index_legacy'),
    path('maintenance/vue-ensemble/',      views.parc_module,                    name='parc_overview'),
    path('maintenance/equipements/',       views.parc_equipements,               name='parc_equipements_legacy'),
    path('maintenance/disponibilite/',     views.parc_disponibilite,             name='parc_disponibilite_legacy'),
    path('maintenance/ordres-maintenance/', views.parc_ordres,                   name='parc_ordres_maintenance'),
    path('maintenance/interventions/',     views.parc_interventions,             name='parc_interventions_legacy'),
    path('maintenance/couts/',             lambda request: redirect('parc_ordres'), name='parc_couts_legacy'),
    path('gasoil/sorties/',         views.gasoil_sorties,        name='gasoil_sorties'),
    path('gasoil/sorties/export/',  views.gasoil_sorties_export, name='gasoil_sorties_export'),
    path('gasoil/sorties/export/csv/', views.gasoil_sorties_csv, name='gasoil_sorties_csv'),
    path('gasoil/sorties/rapport/', views.gasoil_rapport, name='gasoil_rapport'),
    path('gasoil/entrees/',         views.gasoil_entrees,        name='gasoil_entrees'),
    path('gasoil/bilan/',           views.gasoil_bilan,          name='gasoil_bilan'),
    path('qhse/', include('reporting.qhse_urls')),
    path('comptabilite/',                       lambda request: redirect('compta_fournisseurs'), name='compta_index'),
    path('comptabilite/factures-fournisseurs/', views.compta_fournisseurs,   name='compta_fournisseurs'),
    path('comptabilite/factures-client/',       views.compta_factures_client, name='compta_factures_client'),
    path('comptabilite/decaissements/',         views.compta_decaissements,   name='compta_decaissements'),
    path('comptabilite/encaissements/',         views.compta_encaissements,   name='compta_encaissements'),
    path('comptabilite/tresorerie/',            views.compta_tresorerie,      name='compta_tresorerie'),
    path('comptabilite/analyse-projet/',        views.compta_analyse_projet,  name='compta_analyse_projet'),
    path('comptabilite/tva/',                   views.compta_tva,             name='compta_tva'),
    # Alias legacy
    path('comptabilite/entrees/',               views.compta_paid,            name='compta_paid'),
    path('comptabilite/sorties/',               views.compta_unpaid,          name='compta_unpaid'),
    path('comptabilite/bilan/',                 views.compta_tva,             name='compta_tva_legacy'),
    path('chatbot/',                views.chatbot_api,           name='chatbot_api'),
    path('api/soma-ai/chat',        views.chat_soma_ai,          name='chat_soma_ai'),
    # ── Finance & Comptabilité ──────────────────────────────────
    path('finance/',                             lambda r: redirect('finance_dashboard'),                  name='finance_index'),
    path('finance/dashboard/',                   views.finance_dashboard,                                  name='finance_dashboard'),
    path('finance/factures-clients/',            views.finance_factures_clients,                          name='finance_factures_clients'),
    path('finance/factures-fournisseurs/',       views.finance_factures_fournisseurs,                     name='finance_factures_fournisseurs'),
    path('finance/avoirs/',                      views.finance_avoirs,                                    name='finance_avoirs'),
    path('finance/paiements/',                   views.finance_paiements,                                 name='finance_paiements'),
    path('finance/rapports/',                    views.finance_rapports,                                  name='finance_rapports'),
    path('finance/configuration/',               views.finance_configuration,                             name='finance_configuration'),
    path('finance/factures/<int:invoice_id>/',   views.finance_facture_detail,                            name='finance_facture_detail'),
    path('finance/factures/<int:invoice_id>/detail/', views.finance_facture_detail,                       name='finance_facture_detail_page'),
    path('finance/export/factures-clients-excel/',      views.finance_factures_clients_excel,             name='finance_factures_clients_excel'),
    path('finance/export/factures-fournisseurs-excel/', views.finance_factures_fournisseurs_excel,        name='finance_factures_fournisseurs_excel'),
    path('finance/export/paiements-excel/',             views.finance_paiements_excel,                   name='finance_paiements_excel'),
    path('finance/export/factures-clients-pdf/',        views.finance_factures_clients_pdf,               name='finance_factures_clients_pdf'),
    path('finance/export/factures-fournisseurs-pdf/',   views.finance_factures_fournisseurs_pdf,          name='finance_factures_fournisseurs_pdf'),
    path('finance/export/paiements-pdf/',               views.finance_paiements_pdf,                      name='finance_paiements_pdf'),
]
