from django.urls import path
from django.shortcuts import redirect
from . import views

urlpatterns = [
    path('',                        views.accueil,               name='accueil'),
    path('accueil/',                views.accueil,               name='accueil_page'),
    path('transport/',              lambda request: redirect('transport_bons'), name='transport_index'),
    path('production/',             lambda request: redirect('production_index'), name='production_redirect'),
    path('production/production/',          views.production_index,              name='production_index'),
    path('production/gasoil/',              views.production_gasoil,             name='production_gasoil'),
    path('production/couts-par-nature/',    views.production_couts_nature,       name='production_couts_nature'),
    path('transport/bons-transport/',      views.transport_bons,               name='transport_bons'),
    path('transport/gasoil/',              views.transport_gasoil,             name='transport_gasoil'),
    path('transport/couts-par-nature/',    views.transport_couts_nature,       name='transport_couts_nature'),
    path('transport/facturation-client/',  views.transport_facturation_client, name='transport_facturation_client'),
    path('transport/rentabilite/',         views.transport_rentabilite,        name='transport_rentabilite'),
    path('production/facturation-ventes/', views.production_facturation_ventes, name='production_facturation_ventes'),
    path('production/sites/',              views.production_sites,              name='production_sites'),
    path('achats/',                        lambda request: redirect('achats_overview'), name='achats_index'),
    path('achats/vue-ensemble/',           views.achats_overview,               name='achats_overview'),
    path('achats/demandes-achat/',         views.achats_purchase_requests,      name='achats_purchase_requests'),
    path('achats/demandes-prix/',          views.achats_rfq,                    name='achats_rfq'),
    path('achats/bons-commande/',          views.achats_purchase_orders,        name='achats_purchase_orders'),
    path('achats/suivi-livraisons/',       views.achats_delivery_tracking,      name='achats_delivery_tracking'),
    path('achats/fournisseurs/',           views.achats_suppliers,              name='achats_suppliers'),
    path('maintenance/',                   lambda request: redirect('parc_overview'), name='parc_index'),
    path('maintenance/vue-ensemble/',      views.parc_overview,                 name='parc_overview'),
    path('maintenance/equipements/',       views.parc_equipements,              name='parc_equipements'),
    path('maintenance/disponibilite/',     views.parc_disponibilite,            name='parc_disponibilite'),
    path('maintenance/ordres-maintenance/', views.parc_ordres_maintenance,      name='parc_ordres_maintenance'),
    path('maintenance/interventions/',     views.parc_interventions,            name='parc_interventions'),
    path('maintenance/couts/',             views.parc_couts,                    name='parc_couts'),
    path('gasoil/sorties/',         views.gasoil_sorties,        name='gasoil_sorties'),
    path('gasoil/sorties/export/',  views.gasoil_sorties_export, name='gasoil_sorties_export'),
    path('gasoil/sorties/export/csv/', views.gasoil_sorties_csv, name='gasoil_sorties_csv'),
    path('gasoil/sorties/rapport/', views.gasoil_rapport, name='gasoil_rapport'),
    path('gasoil/entrees/',         views.gasoil_entrees,        name='gasoil_entrees'),
    path('gasoil/bilan/',           views.gasoil_bilan,          name='gasoil_bilan'),
    path('qhse/entrees/',           views.qhse_entrees,          name='qhse_entrees'),
    path('qhse/sorties/',           views.qhse_sorties,          name='qhse_sorties'),
    path('qhse/bilan/',             views.qhse_bilan,            name='qhse_bilan'),
]
