# Generated by Django 6.0.4 on 2026-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('equipment_team', models.CharField(blank=True, max_length=255)),
                ('responsible', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('equipment', models.CharField(blank=True, max_length=255)),
                ('intervention_type', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_breakdown', models.DateTimeField(blank=True, null=True)),
                ('date_repair', models.DateTimeField(blank=True, null=True)),
                ('date_planned', models.DateTimeField(blank=True, null=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('maintenance_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Préventive'), ('other', 'Autre')], default='corrective', max_length=50)),
                ('state', models.CharField(choices=[('new', 'Nouvelle demande'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('to_rectify', 'A rectifier les relevés KM')], default='new', max_length=50)),
                ('team', models.CharField(blank=True, max_length=255)),
                ('workshop', models.CharField(blank=True, max_length=255)),
                ('responsible', models.CharField(blank=True, max_length=255)),
                ('driver', models.CharField(blank=True, max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
                ('repair_time', models.CharField(blank=True, max_length=50)),
                ('gap_time', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('maintenance_plan', models.CharField(blank=True, max_length=255)),
                ('intervention_model', models.CharField(blank=True, max_length=255)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('udm', models.CharField(blank=True, max_length=50)),
                ('last_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('sync_date', models.DateTimeField(auto_now=True)),
                ('technicians', models.ManyToManyField(blank=True, to='reporting.technicianemployee')),
            ],
            options={
                'ordering': ['-sync_date', '-id'],
            },
        ),
    ]
